### ISSUE TITLE
Comentários entrega 2

### ISSUE THREAD

**Issue by fabaguiarsilva** [mateuspinto/subnotificacoes-covid#2]
Fizeram uma boa preparação dos dados. Criaram métodos para serem reutilizados.
Só tenho uma sugestão: alguns métodos utilizam iteração, e poderiam ser otimizados usando
map, apply, applymap ou replace (ou alguma outra estratégia do pandas), por exemplo

**Comment by mateuspinto** [comment]
Beleza. Obrigado! :3
